Improve usage documentation
UniversalRobots/Universal_Robots_ROS2_Driver pull request #1110
Opened 2024-09-23 14:57 UTC by fmauch

This aims at implementing #934 and 1044.

This should hopefully significantly improve the usage documentation for end users and clarify a couple of things.

I'm not done, yet, hence the draft status.

2024-09-26 14:07 UTC, urrsk requested changes

2024-09-26 14:07 UTC, urrsk commented on ur_robot_driver/doc/usage/startup.rst
> +* In remote control mode load and start the program using the following dashboard calls:
```suggestion
* In _local control mode_, load the program on the robot and press the "Play" button |play_button| on the teach pendant.
* In _remote control mode_ load and start the program using the following dashboard calls:
```

2024-09-26 14:07 UTC, urrsk commented on ur_robot_driver/doc/usage/startup.rst
> +Whenever the *External Control* program gets interrupted, it has to be unpaused / restarted.
```suggestion
Whenever the *External Control URCap* program gets interrupted, it has to be unpaused / restarted.
```

2024-09-26 14:07 UTC, urrsk commented on ur_robot_driver/doc/usage/startup.rst
> +* In remote control mode start the program using the following dashboard call:
```suggestion
* In _local control mode_, simply press the "Play" button |play_button| on the teach pendant.
* In _remote control mode_ start the program using the following dashboard call:
```

2024-09-26 14:07 UTC, urrsk commented on ur_robot_driver/doc/usage/toc.rst
> +When starting the program on the TP, I get an error "The connection to the remote PC could not be established"
```suggestion
When starting the program on the teach pendant, I get an error "The connection to the remote PC could not be established"
```

2024-09-26 14:07 UTC, urrsk commented
- [ ] Renaming all `ros_control` to `ros2_control`

2024-10-01 07:35 UTC, fmauch commented on ur_robot_driver/doc/operation_modes.rst
> +- (e-series only) The robot's control mode (Local Control Mode vs Remote Control Mode)
I like that very much: "Teach pendant mode"

Maybe we can should make that change at other places, as well.

2024-10-01 09:50 UTC, urrsk approved these changes

2024-10-01 12:13 UTC, merged