Add parameters for checking start state.
UniversalRobots/Universal_Robots_ROS2_Driver pull request #143
Opened 2021-07-12 16:30 UTC by livanov93

This PR comes in combination with [ros2_controlPR128](https://github.com/ros-controls/ros2_control_demos/pull/128).
The idea is to disable execution of test scripts if the start state check has not satisfied configured limits.

2021-07-20 14:34 UTC, destogl approved these changes
This looks good! Thanks!

2021-07-20 16:11 UTC, destogl commented
Waiting for
- ros-controls/ros2_control_demos#128
before merge.

2021-07-30 10:12 UTC, MGBla requested changes
Not sure if the single models differ but on my ur3e i had a different home pose for wrist_1_joint. Otherwise tested it on the real robot and works as expected.

2021-07-30 10:12 UTC, MGBla commented on ur_bringup/config/test_goal_publishers_config.yaml
> +      wrist_1_joint: [-0.1,0.1]
```suggestion
      wrist_1_joint: [-1.6,-1.5] 
```

2021-07-30 10:12 UTC, MGBla commented on ur_bringup/config/test_goal_publishers_config.yaml
> +      wrist_1_joint: [-0.1,0.1]
```suggestion
      wrist_1_joint: [-1.6,-1.5] 
```

2021-08-03 07:16 UTC, urrsk requested changes
Good job.
I can approve with @MGBla correction of wrist_1_joint start angle position

2021-08-13 08:35 UTC, livanov93 commented on ur_bringup/config/test_goal_publishers_config.yaml
> +      wrist_1_joint: [-0.1,0.1]
Resolved with [https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/143/commits/13e2cbad11c9f02dbf158fc5795af6817dee42fa](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/143/commits/13e2cbad11c9f02dbf158fc5795af6817dee42fa)

2021-08-13 08:36 UTC, livanov93 commented on ur_bringup/config/test_goal_publishers_config.yaml
> +      wrist_1_joint: [-0.1,0.1]
Resolved with [https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/143/commits/13e2cbad11c9f02dbf158fc5795af6817dee42fa](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/143/commits/13e2cbad11c9f02dbf158fc5795af6817dee42fa)

2021-08-16 06:03 UTC, urrsk approved these changes

2021-08-17 10:18 UTC, MGBla approved these changes
LGTM

2021-08-18 14:17 UTC, merged