Update controllers adding dt in to update as in ros2_control
UniversalRobots/Universal_Robots_ROS2_Driver pull request #171
Opened 2021-09-19 18:52 UTC by destogl

This PR is related/depends on merge on ros-controls/ros2_control#520 (and ros2_control/ros2_controllers#241)﻿

2021-09-21 06:28 UTC, livanov93 requested changes
Just small change

2021-09-21 06:28 UTC, livanov93 commented on ur_controllers/src/speed_scaling_state_broadcaster.cpp
> +  //   return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;
No return value?

2021-09-21 08:49 UTC, destogl commented on ur_controllers/src/speed_scaling_state_broadcaster.cpp
> +  //   return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;
Thanks for catching this!

2021-09-21 08:50 UTC, destogl commented on ur_controllers/src/speed_scaling_state_broadcaster.cpp
> +  //   return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;
```suggestion
  return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;
```

2021-09-21 09:19 UTC, destogl commented
@livanov93 this seems to be working. Can you give it a try with testing?

2021-09-21 09:22 UTC, livanov93 commented
@destogl It looks good. I can test it with ursim immediately. Hardware test will have to wait.

2021-09-22 12:23 UTC, livanov93 approved these changes
@destogl Tested with ursim on galactic. Works normally.

2021-09-22 14:22 UTC, merged