README badges: Replace markdown table with HTML table
UniversalRobots/Universal_Robots_ROS2_Driver pull request #402
Opened 2022-06-14 10:02 UTC by fmauch

This should be much more maintainable than this very, very overlong markdown lines.

2022-06-15 07:29 UTC, gavanderhoorn commented
You could consider using the non-inline version of the MD links:

```markdown
This is [my link][].

...

[my link]: http://somewhere.something/etc
```

It's certainly more readable -- perhaps even more readable than HTML.

2022-06-20 07:17 UTC, RobertWilbrandt requested changes
This looks fine apart from the typo. I would also prefer a purely markdown-based version, but only if that would also allow splitting the links over multiple lines in the source. Therefore +1 for the HTML solution.

2022-06-20 07:17 UTC, RobertWilbrandt commented on README.md
> +      <a href="https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/galactic-semi-binary-build.ym?query=event%3Aschedule++l">
```suggestion
<a href="https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/galactic-semi-binary-build.yml?query=event%3Aschedule++">
```

2022-06-20 07:24 UTC, fmauch commented
> You could consider using the non-inline version of the MD links:
> 
> ```gfm
> This is [my link][].
> 
> ...
> 
> [my link]: http://somewhere.something/etc
> ```
> 
> It's certainly more readable -- perhaps even more readable than HTML.

It doesn't get really readable once considering that those are image-embedded links. The build status line would be a very long line again:

```markdown
**Build status** | [![Foxy binary build][foxy_binary_badge]][foxy_binary_build] <br/> [![Foxy semi-binary build][foxy_semi-binary_badge]][foxy_semi-binary_build] <br/> [![Foxy source build][foxy_source_badge]][foxy_source_build] <br/> | [![Galactic binary build][galactic_binary_badge]][galactic_binary_build] <br/> [![Galactic semi-binary build][galactic_semi-binary_badge]][galactic_semi-binary_build] <br/> [![Galactic source build][galactic_source_badge]][galactic_source_build] <br/> | [![Humble binary build][humble_binary_badge]][humble_binary_build] <br/> [![Humble semi-binary build][humble_semi-binary_badge]][humble_semi-binary_build] <br/> [![Humble source build][humble_source_badge]][humble_source_build] <br/> | [![Rolling binary build][rolling_binary_badge]][rolling_binary_build] <br/> [![Rolling semi-binary build][rolling_semi-binary_badge]][rolling_semi-binary_build] <br/> [![Rolling source build][rolling_source_badge]][rolling_source_build] <br/>
```

2022-06-20 07:33 UTC, gavanderhoorn commented
Do semantic linefeeds not work for links?

I always have to put empty lines between the badges in my readme, otherwise they get rendered one after the other.

2022-06-20 07:39 UTC, fmauch commented
> Do semantic linefeeds not work for links?

They don't work inside table cells AFAIK.

Obviously, we could split the build status row into three individual rows to circumvent this... @RobertWilbrandt would you consider this a better solution?

I am somewhat undecided, as I don't consider the HTML such a bad thing...

2022-06-20 12:31 UTC, RobertWilbrandt commented
In most cases i would agree that human-readable markdown should be used, but for a table full of github links without any additional content i don't think that really applies. In this specific case i'd say that the HTML table is easier to parse for a human than equivalent markdown, and manual diffing for reviews is also easier.

2022-06-21 11:13 UTC, RobertWilbrandt approved these changes
LGTM

2022-06-22 07:36 UTC, merged