Add mergify rules for backporting
UniversalRobots/Universal_Robots_ROS2_Driver pull request #410
Opened 2022-06-21 07:15 UTC by fmauch

This should enable us to trigger backmerges by simply attaching a label to PRs on main.

2022-06-21 11:09 UTC, RobertWilbrandt requested changes
Do we want an additional ```assignees: ["{{ author }}"]``` rule?

2022-06-21 14:20 UTC, fmauch commented on .github/mergify.yml
> +      - "label=backport-galactic"
That's how I have seen it, but looking at the docs, it might be better to do it as expected...

2022-06-22 07:20 UTC, fmauch commented
> Do we want an additional `assignees: ["{{ author }}"]` rule?

I wouldn't necessarily the author of a PR a suitable assignee for a backport. I'd suggest that we assign these from case to case.

2022-06-22 07:33 UTC, RobertWilbrandt approved these changes
LGTM

2022-06-22 07:35 UTC, merged