Ported controllers to generate_parameters libary and added prefix for controllers (Multiarm part 2)
UniversalRobots/Universal_Robots_ROS2_Driver pull request #594
Opened 2023-02-08 09:22 UTC by firesurfer

This PR is part of splitting up #567  into multiple parts 

This PR ports the gpio controller and the speed scaling state broadcaster to generate_parameter_library

Addtionally it applies the prefix specified in the urdf in order to avoid name clashes.

NOTE: If really necessary this work could be split up into two PRs (one for the prefix, one for the  generate_parameter  library) but this would be a lot of work for just a small benefit.

2023-04-24 13:33 UTC, fmauch commented
@firesurfer yes, reverting that seems reasonable. Would you like to do that and I'll review it afterwards? Thanks!

2023-04-25 06:38 UTC, firesurfer commented
@fmauch I just reverted the behaviour to the default behaviour

2023-05-08 14:29 UTC, fmauch requested changes
As far as I can see, the proposed changes would break a couple of things. We should make sure that everything is running together with this PR applied.

2023-05-08 14:29 UTC, fmauch commented on ur_controllers/CMakeLists.txt
> +  #src/scaled_joint_trajectory_controller.cpp
The scaled JTC should not get removed in this PR.

2023-05-08 14:29 UTC, fmauch commented on ur_controllers/src/speed_scaling_state_broadcaster_parameters.yaml
> +    description: "rate the speedscaling state will be updated"
```suggestion
    description: "Rate at which the speedscaling state will be published."
```

2023-05-08 14:29 UTC, fmauch commented on ur_robot_driver/src/hardware_interface.cpp
> +
What happened to this? This change seems like it would break everything.

2023-05-11 14:04 UTC, fmauch approved these changes
Looks good to me and tested this locally. Thank you @firesurfer for the continuous effort!

2023-05-12 06:55 UTC, merged

2023-05-26 08:42 UTC, fmauch commented
@Mergifyio backport humble